# Generated by Django 4.2 on 2023-06-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_likecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likecount',
        ),
    ]
