# Generated by Django 4.2 on 2023-05-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_category_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('choose', 'Choose a category'), ('Art', 'Art'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Health & Fitness', 'Health & Fitness'), ('Home', 'Home'), ('Travel', 'Travel'), ('Other', 'Other')], default='choose a category', max_length=30),
        ),
    ]
