# Generated by Django 4.2 on 2023-05-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auction_category_delete_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
