# Generated by Django 4.2 on 2023-06-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
    ]
